Repository ExpediaGroup/stream-registry, pull requests merged in 2018-12, with the labels that each got.

#39 Integrating with travis-ci
  .travis.yml
  CHANGELOG.md
  Makefile
  README.md
  assembly/pom.xml
  core/pom.xml
  core/src/main/java/com/homeaway/streamingplatform/health/StreamRegistryHealthCheck.java
  kafka-infra-provider/pom.xml
  kafka-infra-provider/src/main/java/com/homeaway/streamingplatform/provider/impl/KafkaInfraManager.java
  pom.xml
  schema-library-events/pom.xml
Labels: enhancement

#45 Removed shell script in favor of Makefile
  CHANGELOG.md
  Makefile
  README.md
  core/src/main/java/com/homeaway/streamingplatform/StreamRegistryApplication.java
  docs/docs/usage/index.md
  stream-registry.sh
Labels: documentation, enhancement

#48 Fixing release:perform
  CHANGELOG.md
  pom.xml
Labels: bug, enhancement

#50 Addressing ossrh build requirements
  CHANGELOG.md
  assembly/pom.xml
  core/pom.xml
  kafka-infra-provider/pom.xml
  pom.xml
  schema-library-events/pom.xml
Labels: bug, enhancement

#51 Forcing javadoc for assembly-jar
  CHANGELOG.md
  assembly/src/main/java/com/homeaway/streamingplatform/streamregistry/shaded/DummyForJavaDoc.java
  pom.xml
Labels: bug, enhancement

#54 Fixing README
  CHANGELOG.md
  README.md
  docs/docs/index.md
Labels: documentation

#57 Fixing master build on travis-ci
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .travis.yml
  .travis/settings.xml
  .travis/setup-deploy.sh
  CHANGELOG.md
  Makefile
Labels: bug, enhancement

#64 Updating healthcheck info
  CHANGELOG.md
  core/src/main/java/com/homeaway/streamingplatform/StreamRegistryApplication.java
  docs/docs/usage/index.md
Labels: documentation

#65 README updates with Kafka Version details
  README.md
Labels: documentation

#69 Fixing unused stream name path param
  CHANGELOG.md
  core/src/main/java/com/homeaway/streamingplatform/health/StreamRegistryHealthCheck.java
  core/src/main/java/com/homeaway/streamingplatform/resource/StreamResource.java
  core/src/test/java/com/homeaway/streamingplatform/extensions/schema/SchemaManagerIT.java
  core/src/test/java/com/homeaway/streamingplatform/extensions/validator/StreamValidatorIT.java
  core/src/test/java/com/homeaway/streamingplatform/resource/ConsumerResourceIT.java
  core/src/test/java/com/homeaway/streamingplatform/resource/ProducerResourceIT.java
  core/src/test/java/com/homeaway/streamingplatform/resource/StreamResourceIT.java
Labels: bug

#70 Removed unused retrofit library
  CHANGELOG.md
  pom.xml
Labels: enhancement

#68 Favor mvn exec rather than java jar
  Makefile
  pom.xml
Labels: enhancement
