Repository ExpediaGroup/stream-registry, pull requests merged in 2019-02, with the labels that each got.

#99 Publish the docker image
  CHANGELOG.md
  assembly/pom.xml
Labels: enhancement

#101 Failing healthcheck
  CHANGELOG.md
  core/src/main/java/com/homeaway/streamplatform/streamregistry/extensions/schema/ConfluentSchemaManager.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/extensions/schema/SchemaManagerIT.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheckIT.java
Labels: bug

#108 refactored the way configs are passed to SchemaRegistryClient to make…
  core/src/main/java/com/homeaway/streamplatform/streamregistry/StreamRegistryApplication.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/extensions/schema/ConfluentSchemaManager.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/extensions/schema/SchemaManager.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheckIT.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/resource/BaseResourceIT.java
Labels: enhancement

#111 BIGDATA-6059: Formatted the error responses so that the developers can debug the errors easily
  CHANGELOG.md
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/KafkaManagerImpl.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/StreamDaoImpl.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/resource/ConsumerResource.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/resource/ProducerResource.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/resource/StreamResource.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/StreamDaoImplTest.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/resource/ConsumerResourceIT.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/resource/ProducerResourceIT.java
Labels: enhancement

#102 Hardening check for ensuring KStream store is available during IT phase
  CHANGELOG.md
  core/src/main/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheck.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/resource/BaseResourceIT.java
Labels: enhancement

#118 Some TODO and Cleanup
  core/src/main/java/com/homeaway/streamplatform/streamregistry/StreamRegistryApplication.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/KafkaManager.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/StreamDao.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/KafkaManagerImpl.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/StreamDaoImpl.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/exceptions/StreamCreationException.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/model/Tags.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/extensions/schema/SchemaManagerIT.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/resource/BaseResourceIT.java
  core/src/test/resources/logback-test.xml
  mvnw
  pom.xml
Labels: documentation

#120 HealthCheck not working
  CHANGELOG.md
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/AbstractDao.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheck.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/streams/ManagedKStreams.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/resource/BaseResourceIT.java
Labels: bug

#126 modifying error message for stream name mismatch during upsert
  core/src/main/java/com/homeaway/streamplatform/streamregistry/resource/StreamResource.java
Labels: enhancement

#128 Adding NonNull constraint check for InfraManagerConfig.config
  CHANGELOG.md
  core/src/main/java/com/homeaway/streamplatform/streamregistry/configuration/InfraManagerConfig.java
Labels: enhancement

#124 Hardening dependency injection to ensure services start and stop in order
  CHANGELOG.md
  core/src/main/java/com/homeaway/streamplatform/streamregistry/StreamRegistryApplication.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/StreamRegistryManagedContainer.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/AbstractDao.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/ConsumerDaoImpl.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/KafkaManagerImpl.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/ProducerDaoImpl.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/StreamDaoImpl.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/streams/ManagedInfraManager.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/StreamDaoImplTest.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/resource/BaseResourceIT.java
Labels: enhancement

#127 added helm chart for deploying stream registry
  .gitignore
  charts/.helmignore
  charts/Chart.yaml
  charts/OWNERS
  charts/README.md
  charts/requirements.yaml
  charts/templates/NOTES.txt
  charts/templates/deployment.yaml
  charts/templates/ingress.yaml
  charts/templates/service.yaml
  charts/values.yaml
Labels: enhancement
