Repository ExpediaGroup/stream-registry, pull requests merged in 2019-01, with the labels that each got.

#76 Fix 'make run'
  CHANGELOG.md
  pom.xml
Labels: bug

#74 Dockerize
  CHANGELOG.md
  Makefile
  README.md
  assembly/pom.xml
  assembly/src/main/jib/app/stream-registry-config.yaml
  docker-compose.yml
  pom.xml
Labels: enhancement

#52 Stop Stream Creation for existing topics if configs don't match
  CHANGELOG.md
  core/pom.xml
  core/src/main/java/com/homeaway/streamingplatform/configuration/KafkaProducerConfig.java
  core/src/main/java/com/homeaway/streamingplatform/db/dao/KafkaManager.java
  core/src/main/java/com/homeaway/streamingplatform/db/dao/impl/KafkaManagerImpl.java
  core/src/main/java/com/homeaway/streamingplatform/db/dao/impl/StreamDaoImpl.java
  core/src/test/java/com/homeaway/streamingplatform/db/dao/impl/KafkaManagerImplTest.java
  pom.xml
Labels: enhancement

#80 Adding arch diagram to fix #4
  CHANGELOG.md
  README.md
  docs/docs/architecture/StreamRegistryArchitecture.png
Labels: documentation

#78 Decouple infra-provider from core
  .travis.yml
  CHANGELOG.md
  assembly/pom.xml
  core/pom.xml
  core/src/main/java/com/homeaway/streamingplatform/provider/InfraManager.java
  infra-provider-kafka/pom.xml
  infra-provider-kafka/src/main/java/com/homeaway/streamingplatform/provider/impl/KafkaInfraManager.java
  infra-provider/pom.xml
  infra-provider/src/main/java/com/homeaway/streamingplatform/provider/InfraManager.java
  pom.xml
  schema-library-events/pom.xml
Labels: enhancement

#82 Enforce SLF4J
  CHANGELOG.md
  pom.xml
Labels: enhancement

#73 Bug/delete client error fix
  CHANGELOG.md
  core/src/main/java/com/homeaway/streamingplatform/db/dao/impl/ConsumerDaoImpl.java
  core/src/main/java/com/homeaway/streamingplatform/db/dao/impl/ProducerDaoImpl.java
  core/src/main/java/com/homeaway/streamingplatform/utils/StreamRegistryUtils.java
  core/src/test/java/com/homeaway/streamingplatform/utils/StreamRegistryUtilsTest.java
Labels: bug

#88 Fix Schema Registry URL in Docker Compose
  docker-compose.yml
Labels: bug

#89 documentation: fix repo name
  docs/mkdocs.yml
Labels: enhancement

#90 Preparing build issues for openjdk11
  .travis.yml
  CHANGELOG.md
  Makefile
  core/pom.xml
  core/src/main/java/com/homeaway/streamplatform/streamregistry/lombok.config
  core/src/test/java/com/homeaway/streamplatform/streamregistry/db/dao/impl/KafkaManagerImplTest.java
  pom.xml
Labels: enhancement

#91 Preparing build issues for openjdk11
  CHANGELOG.md
  README.md
Labels: documentation, enhancement

#92 Doc typo
  docs/docs/architecture/index.md
Labels: documentation

#95 Fixing healtcheck by sending appropriate key/value schemas
  CHANGELOG.md
  core/src/main/java/com/homeaway/streamplatform/streamregistry/extensions/schema/ConfluentSchemaManager.java
  core/src/main/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheck.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/health/StreamRegistryHealthCheckIT.java
  core/src/test/java/com/homeaway/streamplatform/streamregistry/resource/BaseResourceIT.java
Labels: enhancement
